# 10장 - 예외 처리

- 잡히지 않은 예외가 발생하면 프로그램은 종료됨.
- 코루틴도 잡히지 않은 예외가 발생했을 때 종료됨.
    - 코루틴 빌더는 부모도 종료시키며, 취소된 부모는 자식들 모두를 취소시킴.
    - 코루틴이 예외를 받았을 때 자기 자신을 취소하고 예외를 부모에게 전파함.
        - 즉, 예외는 자식에서 부모로 전파됨.
        - 부모가 취소되면 자식도 취소되기 때문에 쌍방으로 전파됨.
    - 예외 전파가 정지되지 않으면 모든 코루틴이 취소됨.

## 코루틴 종료 멈추기

- 코루틴 간의 상호작용은 Job을 통해서 일어남.
- 코루틴 빌더 내부에서 새로운 코루틴 빌더를 try-catch를 통해 래핑하는건 도움이 안됨.

```kotlin
suspend fun main(): Unit = coroutineScope {
    try {
        launch {
            throw NullPointerException()
            repeat(10) {
                println(it)
            }
        }
        delay(1000)
        println("끝")
        delay(1000)
    } catch(e: Exception) {
        println("test")
    }
}
```

- launch에서 예외가 전파돼 `coroutineScope` 에선 해당 예외가 잡히지만, `launch` 블록에선 잡히지 않아

NullPointerException가 발생하게됨.

```kotlin
suspend fun main(): Unit = coroutineScope {
    try {
        launch {
            try {
                throw NullPointerException()
                repeat(10) {
                    println(it)
                }
            } catch (e: Exception) {
                println("test1")
            }

        }
        delay(1000)
        println("끝")
        delay(1000)
    } catch(e: Exception) {
        println("test")
    }
}
```

- 위 처럼 `launch` 블록에도 try~catch를 사용한다면, 해당 블록에서 예외가 잡히므로 `coroutineScope` (부모코루틴)까지 전파가 안됨.
    - 즉 실행결과는 test1이 나옴.

## SupervisorJob

- 코루틴 종료를 멈추는 가장 중요한 방법은 `SupervisorJob` 을 사용하는 것.
- `SupervisorJob` 을 사용하면 자식에서 발생한 모든 예외를 무시할 수 있음.
- 일반적으로 `SupervisorJob` 은 다수의 코루틴을 시작하는 스코프로 사용됨.

```kotlin
fun main(): Unit = runBlocking {
     launch(SupervisorJob()) { 
         launch {
             delay(1000)
             throw Error("Some error")
         }
             
         launch { 
             delay(2000)
             println("Will not be printed")
         }
     }
     delay(3000)
}
```

- 흔한 실수는 위 코드처럼 `SupervisorJob` 을 다음 코드처럼 부모 코루틴의 인자로 사용하는 것임.
- `SupervisorJob` 은 단 하나의 자식만 가지기 때문에 예외를 처리하는데 아무런 도움이 되지 않음.

## supervisorScope

- 예외 전파를 막는 또 다른 방법은 코루틴 빌더를 `supervisorScope`로 래핑하는 것임.
- 다른 코루틴에서 발생한 예외를 무시하고 부모와의 연결을 유지한다는 점에서 아주 편리함.

```kotlin
fun main(): Unit = runBlocking {
     supervisorScope {
         launch {
             delay(1000)
             throw Error("Some error")
         }

         launch {
             delay(2000)
             println("Will not be printed")
         }
     }
     delay(3000)
}
```

- `supervisorScope`는 `withContext(SupervisorJob()`)으로 대체될 수 없음.

## CancellationException은 부모까지 전파되지 않는다

- 예외가 `CancellationException`의 서브 클래스라면 부모로 전파되지 않음.
    - 현재 코루틴을 취소시킬 뿐임.
- `CancellationException` 는 `open class`여서 다른 클래스나 객체로 확장이 가능함.

## 코루틴 예외 핸들러

- 예외를 다룰 때 예외를 처리하는 기본 행동을 정의하는 것이 유용할 때가 있음.
- 이런 경우 `CoroutineExceptionHandler` 컨텍스트를 사용하면 편리함.

```kotlin
val ceh = CoroutineExceptionHandler { coroutineContext, exception -> 
    print("Caught $exception")
}

fun main(): Unit = runBlocking {
     val scope = CoroutineScope(SupervisorJob() + ceh)
     scope.launch { 
         delay(1000)
         throw Error("Some Error")
     }
     scope.launch { 
         delay(2000)
         print("Will be printed")
     }
     delay(3000)
}
```

## 궁금한 것

1. 114p 코루틴 예외 전파에 대해서 그림
    1. #6코루틴에서 예외가 발생하면, 부모인 #3에 전파되고 #3은 #1로 전파되는데, 이 때 #3에서 #6에 예외를 전파하는건가?
2. 이건 갑자기 헷갈려서! 코루틴 빌더와 코루틴 스코프의 차이점?
    1. 코루틴 스코프 내에서 코루틴 빌더 사용가능
    2. 코루틴 빌더내에서 코루틴 빌더 사용 가능
    3. 일시 중단 함수에서 코루틴 스코프 사용 가능
3. 기초적인 질문인데 갑자기 헷갈려서..ㅎㅎ 121p 코드에서 만약 주석2번 launch에서 딜레이 걸리면  주석4번 launch가 실행되는 구조?
    1. 만약에 주석1번 launch에서 여러개의 launch가 있다면 어떻게 실행될까요?
    2. coroutineScope까지 예외 전파가 안되는지?
