# 일시중단 함수 구성하기

### 기본적인 순차처리

- 코루틴을 동기식으로 호출 하려면 어떻게 해야할까?
    - A함수의 결과를 B함수에서 사용해야하는 상황이라면, 순차처리를 해야함.
- 일반적인 코드와 같이 코루틴 코드도 기본적으로는 순차적으로 처리함.
- 다음 예제는 두 일시 중단 함수를 실행하는데 걸리는 총 시간을 측정한 것.
    - 각 함수에서 `delay` 함수를 1초간 호출 하므로 약2초의 시간이 측정됨.

```kotlin
fun main()  = runBlocking {
    val times = measureTimeMillis {
        val one = doSomethingUsefulOne()
        val two = doSomethingUsefulTwo()
        println("The answer is ${one + two}")
    }
    println("Completed in $times ms")
}

suspend fun doSomethingUsefulOne(): Int {
    delay(1000)
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000)
    return 29
}

// The answer is 42
// Completed in 2017 ms
```

### async를 사용한 동시성

- 위 두 함수간 실행시 종속성이 없고, 둘을 동시에 실행하여 응답을 빠르게 얻고싶은 경우 `async` 함수를 사용할 수 있음.
    - 개념적으로 `async` 는 `launch` 와 같지만, 다른점은
        - `launch` : 결과값을 전달하지 않는 `Job`을 리턴함.
        - `async` : 결과값을 반환하는 `Deffered`를 리턴함.
            - `await` 함수를 사용하여 결과값을 얻을 수 있음.
            - `Deffered` 는 결과값을 수신하는 비동기 작업임. 이는 `Job` 의 모든 속성을 가지고 있음.
                - 즉, 필요할 땐 취소될 수 있음.

```kotlin
fun main()  = runBlocking {
    val times = measureTimeMillis {
        val one = async { doSomethingUsefulOne() }
        val two = async { doSomethingUsefulTwo() }
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $times ms")
}

// The answer is 42
// Completed in 1015 ms
```

### async lazy하게 시작하기

- `async` 함수의 파라미터 값을 CoroutineStart.LAZY로 설정할 수 있음.
    - `CoroutineStart.LAZY`로 시작된 `async`는 자동으로 시작되지 않음.
    - 이는 `async` 를 lazy하게 만듦. 즉, 개발자가 언제 실행하게 할 것인지 트리거할 수 있는 제어 권한이 주어짐.
        - `start` 가 트리거 역할을 함.
            - 이는 해당 코루틴을 명시적으로 시작하는데 사용함.

```kotlin
fun main()  = runBlocking {
    val time = measureTimeMillis {
        val one = async(start = CoroutineStart.LAZY) { doSomethingUsefulOne() }
        val two = async(start = CoroutineStart.LAZY) { doSomethingUsefulTwo() }
        one.start() 
        two.start() 
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")
}

// The answer is 42
// Completed in 1015 ms
```

- `async` 를 lazy하게 실행할 때, 코루틴은 즉시 실행되지 않음.
    - 코루틴을 실행하는 트리거(`start`, `await`)이 호출되어야 코루틴이 실행됨.
    - `start` 를 사용하지 않고, `await` 만 사용한 경우 이는 순차적으로 처리됨.
        - `await` 은 코루틴을 시작하고 완료를 기다리기 때문.

### 비동기 스타일 함수

- `GlobalScope` 를 참조하는 `async` 코루틴 빌더를 사용해 비동기 스타일의 함수를 정의할 수 있음.
    - `GlobalScope` 사소하지 않은 역효과를 일으킬 수 있음. → 사용을 지양하자.
        - https://thdev.tech/kotlin/2020/12/22/kotlin_effective_16/

```kotlin
@OptIn(DelicateCoroutinesApi::class)
fun somethingUsefulOneAsync() = GlobalScope.async {
    doSomethingUsefulOne()
}
```

- 위 코드처럼 만들 수 있는데, 이는 일시중단 함수가 아님. 따라서 코루틴 블록이 아닌 다른곳에서도 호출이 가능함.
    - 해당 함수들의 동작은 언제나 비동기적(동시성)임.

### 구조화된 동시성과 async

```kotlin
fun main() = runBlocking {
    val times = measureTimeMillis {
        println("The answer is ${concurrentSum()}")
    }
    println("Completed in $times ms")
}

suspend fun concurrentSum(): Int = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}

// The answer is 42
// Completed in 1018 ms
```

위 코드처럼 `coroutineScope` 로 함수를 작성하면 `concurrentSum` 함수 내부에서 예외가 발생 되었을 때, 스코프 내부에서 실행된 모든 코루틴들이 취소됨.

### 취소는 언제나 코루틴의 계층 구조를 통해 전파된다

```kotlin
fun main() = runBlocking<Unit> {
    try {
        failedConcurrentSum()
    } catch (e: ArithmeticException) {
        println("Computation failed with ArithmeticException")
    }
}

suspend fun failedConcurrentSum(): Int = coroutineScope {
    val one = async {
        try {
            delay(Long.MAX_VALUE)
            42
        } finally {
            println("First child was cancelled")
        }
    }
    val two = async<Int> {
        println("Second child throws an exception")
        throw ArithmeticException()
    }
    one.await() + two.await()
}

// Second child throws an exception
// First child was cancelled
// Computation failed with ArithmeticException
```

- one의 `async` 블록에는 `delay` 를 Long의 최댓값을 부여하고 있고, 일시 중단이 끝날 경우에 `finllay` 가 호출될 것임.
- two의 `async` 블록에는 예외를 던져주고 있음.
    - 자식들 중 하나가 취소로 인해 실패하면 발생지점 부터 부모 코루틴까지 예외가 전파되어 코루틴이 취소됨.
        - 즉, Long의 최댓값을 딜레이중인 one과 `await` 을 수행중인 부모가 모두 취소됨.
```kotlin
one과 two의 위치만 바뀌보면, two에서 예외가 바로 발생하기 때문에 바로 코루틴이 취소되어 one은 호출되지 않음.
```
