# 취소와 타임아웃

### Coroutine 실행 취소하기

- 백그라운드에서 오랜시간 유지되는 코루틴에 대한 세밀한 제어가 필요할 수 있음.
    - 코루틴을 실행시킨 페이지를 닫아 결과가 필요하지 않은 경우
- `launch` 는 실해중인 코루틴을 취소하는데 사용하는 `Job` 객체를 반환함.

```kotlin
import kotlinx.coroutines.*

fun main() = runBlocking {
    val job = launch {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    }
    delay(1300L) 
    println("main: I'm tired of waiting!")
    job.cancel() // Job을 cancel한다.
    job.join() // Job의 실행(취소)이 완료될 때까지 기다린다.
		// job.cancelAndJoin()
    println("main: Now I can quit.")
}
```

- `cancel` : 해당 범위(코드블록)의 코루틴을 취소함.
    - 범위에 작업이 없다면 `IllegalStateException` 이 발생함.
    - 취소 시점으로부터 첫 번째 중단 지점부터 취소가 이뤄짐.
        - 즉, 즉시 중지되지 않음.
- `join` : 코루틴의 동작이 완료될 때 까지 대기함.
    - 위 코드에선 취소를 기다리기 위해 사용.
- `cancelAndJoin` : `cancel` 과 `join` 을 결합한 함수임.

```kotlin
cancel을 하고 join을 안해준 경우엔 cancel 이후의 코드가 코루틴이 완전히 종료되기 전에 실행될 가능성이 있음.
```

### Coroutines 취소는 협력적이다

- 코루틴의 취소는 협력적이며, 코루틴 코드는 취소 가능하도록 협력해야함.
- `kotlin.coroutines` 패키지의 모든 일시 중단 함수들은 **취소가 가능**함.
    - 코루틴이 취소되었는지 확인하고 취소되었을 경우 `CancellationException` 을 발생시킴.
        - 즉 `cancel` 함수 호출 시 발생함.
        - `CancellationException` 예외는 일시 중단 함수가 있을 경우에만 발생함.
    - `CancellationException` 예외는 코루틴 라이브러리에서 `catch` 하고, 코루틴을 종료시킴.
        - 코루틴의 취소를 처리해야하는 경우 `try-catch` 를 사용하면 됨.
- 코루틴이 계산작업 중이고 취소를 확인하지 않는다면 다음 예시처럼 취소될 수 없음

```kotlin
import kotlinx.coroutines.*

fun main() = runBlocking {
    val startTime = System.currentTimeMillis()
    val job = launch(Dispatchers.Default) {
        var nextPrintTime = startTime
        var i = 0
        while (i < 5) { // 계산 루프, CPU를 낭비한다
            // 1초에 두 번 메세지를 출력한다.
            if (System.currentTimeMillis() >= nextPrintTime) {
                println("job: I'm sleeping ${i++} ...")
                nextPrintTime += 500L
            }
        }
    }
    delay(1300L) // 약간의 시간 동안 delay 한다
    println("main: I'm tired of waiting!")
    job.cancelAndJoin() // Job을 취소하고 실행이 완료될 때까지 기다린다.
    println("main: Now I can quit.")    
}

// 이 코드는 취소했음에도 I'm sleeping이 출력되는 이유는 cancel호출시 중단지점이 없음.
```

```kotlin
출력결과 :
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
job: I'm sleeping 3 ...
job: I'm sleeping 4 ...
main: Now I can quit.
```

위 처럼 취소를 했음에도, I'm sleeping이 계속 출력됨.

```kotlin
위와 같은 문제는 CancellationException을 catch하고 다시 throw 하지 않는 경우에도 발생함.

try {
    ... 
} catch (e: CancellationException) {
    throw e
}
```

### Coroutine의 Computation 코드를 취소 가능하게 만들기

- 계산중인 코루틴 코드를 취소 가능하게 만드는 방식은 두가지가 있음.
    - 주기적으로 일시 중단 함수를 실행시켜 취소되었는지 확인.
        - `yield` 함수
    - 명시적으로 취소 상태를 확인

```kotlin
// 명시적으로 취소 상태를 확인하는 예시
val job = launch(Dispatchers.Default) {
        var nextPrintTime = startTime
        var i = 0
        while (isActive) { // 취소 가능한 computation loop
            // 1초에 두 번 메세지를 출력한다.
            if (System.currentTimeMillis() >= nextPrintTime) {
                println("job: I'm sleeping ${i++} ...")
                nextPrintTime += 500L
            }
        }
    }
```

- `isActive` 는 `CoroutineScope` 객체를 통해 코루틴 내부에서 사용할 수 있는 확장 프로퍼티임.
    - 현재 코루틴이 아직 완료되지 않았다면 true를 반환함.

### finally 사용해 리소스 닫기

- `try-finally` 구문이나, `use` 함수는 코루틴이 취소될 때 정상적으로 종료 작업을 수행함.
    - `cancelAndJoin` 함수가 호출되면서 코루틴이 종료 작업을 기다림 →  `finally` 나 `use` 블록을 실행시킴.

### 실행 취소가 불가능한 블록 실행하기

- 드물게 취소된 코루틴에 대해 일시 중단을 해야하는 경우는 `withContext` 함수에 `NonCancellable` Context를 전달하여 사용함.

```kotlin
fun main() = runBlocking {
    val job = launch {
        try {
            repeat(1000) { i ->
                println("job: I'm sleeping $i ...")
                delay(500L)
            }
        } finally {
            withContext(NonCancellable) {
                println("job: I'm running finally")
                delay(1000L)
                println("job: And I've just delayed for 1 sec because I'm non-cancellable")
            }
        }
    }
    delay(1300L) // delay a bit
    println("main: I'm tired of waiting!")
    job.cancelAndJoin() // cancels the job and waits for its completion
    println("main: Now I can quit.")
}
```

```kotlin
실행결과
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
job: I'm running finally
main: Now I can quit.
```

- `finally` 에서 `delay` 함수 호출시 `CancellationException` 이 발생하므로 다음 `println` 문이 실행이 안되어야 정상임.
    - `withContext(NonCancellable)` 을 사용하여 취소된 코루틴에 대해 일시 중단을 실행시킴.

### Timeout

- 지정된 시간을 정의해 일정 시간 이후에 참조된 Job을 취소하는 `withTimeout` 함수가 있음.

```kotlin
import kotlinx.coroutines.*

fun main() = runBlocking {
    withTimeout(1300L) { 
        repeat(1000) { i ->
            println("I'm sleeping $i ...")
            delay(500L)
        }
    }
}

// val result = withTimeoutOrNull(1300L) { ... }
```

- 시간이 초과하면 `TimeoutCancellationException` 을 발생시킴. → 무조건 발생
    - 주어진 시간이 양수가 아니면 즉시 `TimeoutCancellationException` 을 발생시킴.
    - `TimeoutCancellationException` 이는 `CancellationException`의 서브클래스임.
    - 시간 초과시 예외를 발생시키지 않게 사용하려면 `withTimeoutOrNull` 을 사용하면 됨.
        - 이는 시간 초과시 예외를 발생시키지 않고, `null`을 반환함.
